### ISSUE TITLE
NotifyListeners being called on disposed ViewModel

### ISSUE THREAD

**Issue by thaoula** [Stacked-Org/stacked#36]
Hi Team,

Firstly, thanks for the library and the youtube channel. 

I have been using the provider model and a variation of your initial framework for a couple of months and I am in the process of migrating to Stacked.

A common scenario we seem to experience is the following -
1. Widget calls function in ViewModel
2. View Model makes async call 
3. User navigates somewhere else before the async call is finished.
4. Async call finishes
5. Dart then continues running the code in the view model .. with the next line after the async call being notifyListeners.

The issue we are having is that we get an exception complaining about the ViewModel being disposed and that we should not call notify listeners.

I have solved this issue using the following code which is basically my own class that extends your BaseViewModel -

`
class BaseViewModelExtended extends BaseViewModel {
  
  bool _disposed = false;
  bool get disposed => _disposed;

  void notifyListeners() {
    safeNotifyListeners();
  }

  void safeNotifyListeners() {
    if (!disposed) super.notifyListeners();
  }

  @override
  void dispose() {
    super.dispose();
    _disposed = true;
  }
}
`
I am happy to know if I am missing something so I can correct the code. Otherwise, could you consider adding something similar to stacked?

Regards,
Tarek

**Comment by FilledStacks** [comment]
Yes, This is something that I will be adding as well. I was supposed to work on the new tutorial today. Having some client product issues with firebase, once that's out of the way I will implement something for this in the base viewmodel and push that. 

Thanks for filing the issue. It serves as a reminder.

**Comment by thaoula** [comment]
Thanks

I keep hitting the refresh button on youtube waiting for your tutorial :)

**Comment by FilledStacks** [comment]
Haha. I'm so excited to share it. I've finished one section there's still two left.

**Comment by FilledStacks** [comment]
@lakshanmamalgaha No, there's a workaround above. Haven't had time to add it yet

**Comment by FilledStacks** [comment]
@lakshanmamalgaha this has been fixed in 1.6.0

**Comment by dulajdanu** [comment]
I Still get this error in 1.7.6 "FlutterError (A PreviousCheckInLocationWidgetViewModel was used after being disposed.
Once you have called dispose() on a PreviousCheckInLocationWidgetViewModel, it can no longer be used.)"

**Comment by FilledStacks** [comment]
@dulajdanu that means your Viewmodel is disposed. You can set `disposeViewModel` to false on your ViewModelBuilder widget.
